# version: '3.8'
services:
  backend:
    build: ./backend/
    container_name: blog-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=8000
      - NODE_ENV=development
    volumes:
      - "./backend/:/app"
      - "/app/node_modules"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: blog-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mongo:6
    container_name: blog-db
    restart: always

volumes:
  db-data: {}