services:
  backend:
    build: ./backend/
    container_name: blog-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=8000
      - NODE_ENV=development
    volumes:
      - "./backend/:/app"
      - "/app/node_modules"

  frontend:
    build: ./frontend
    container_name: blog-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
